apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Chart.Name }}-service"
  namespace: {{ .Values.namespace }}
  labels:
    service: "{{ $.Chart.Name }}-app"
  annotations:
    traefik.ingress.kubernetes.io/affinity: "false"
spec:
  ports:
    - port: 80
      name: web-app
      targetPort: web-app
      protocol: TCP
  selector:
    service: "{{ $.Chart.Name }}-app"