"use client";

import React, { useState, useEffect } from "react";
import Navbar from "@/components/Navbar";
import Link from "next/link";

const definitions = [
    { term: "Cookie", definition: "small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information." },
    { term: "Company", definition: "when this policy mentions 'Company', 'we', 'us' or 'our', it refers to Blockchain Centre Nairobi and Wada Kenya, that is responsible for your information under these Terms & Conditions." },
    { term: "Country", definition: "where Cardano Africa Tech Summit or the owners/founders of Cardano Africa Tech Summit are based, in this case it is Kenya." },
    { term: "Device", definition: "any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Cardano Africa Tech Summit and use the services." },
    { term: "Service", definition: "refers to the service provided by Cardano Africa Tech Summit as described in the relative terms (if available) and on this platform." },
    { term: "Third-party service", definition: "refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you." },
    { term: "Website", definition: "Cardano Africa Tech Summit's site, which can be accessed via this URL: https://cats.wada.org/" },
    { term: "You", definition: "a person or entity that is registered with Cardano Africa Tech Summit to use the Services." },
];

const menuItems = [
    { label: "General Terms", id: "general" },
    { label: "License", id: "license" },
    { label: "Definitions & Key Terms", id: "definitions" },
    { label: "Restrictions", id: "restrictions" },
    { label: "Payment", id: "payment" },
    { label: "Return and Refund Policy", id: "refund" },
    { label: "Your Suggestions", id: "suggestions" },
    { label: "Links to Other Websites", id: "links" },
    { label: "Cookies", id: "cookies" },
    { label: "Changes To Our Terms & Conditions", id: "changes" },
    { label: "Modifications to Our website", id: "modifications" },
    { label: "Updates to our website", id: "updates" },
    { label: "Third-Party Services", id: "thirdparty" },
    { label: "Term and Termination", id: "termination" },
    { label: "Copyright Infringement Notice", id: "copyright" },
    { label: "Indemnification", id: "indemnification" },
    { label: "No Warranties", id: "warranties" },
    { label: "Limitation of Liability", id: "liability" },
    { label: "Severability", id: "severability" },
    { label: "Waiver", id: "waiver" },
    { label: "Amendments to this Agreement", id: "amendments" },
    { label: "Entire Agreement", id: "entire" },
    { label: "Updates to Our Terms", id: "updates-terms" },
    { label: "Intellectual Property", id: "ip" },
    { label: "Agreement to Arbitrate", id: "arbitrate" },
    { label: "Notice of Dispute", id: "dispute" },
    { label: "Binding Arbitration", id: "binding" },
    { label: "Submissions and Privacy", id: "submissions" },
    { label: "Promotion", id: "promotion" },
    { label: "Typographical Errors", id: "typo" },
    { label: "Miscellaneous", id: "miscellaneous" },
    { label: "Disclaimer", id: "disclaimer" },
    { label: "Contact Us", id: "contact" },
];

export default function TermsPage() {
    const [activeSection, setActiveSection] = useState<string>("general");

    const scrollToSection = (e: React.MouseEvent<HTMLAnchorElement>, id: string) => {
        e.preventDefault();
        const element = document.getElementById(id);
        if (element) {
            element.scrollIntoView({ behavior: "smooth", block: "center" });
            window.history.pushState(null, "", `#${id}`);
        }
    };

    useEffect(() => {
        const observerOptions = {
            root: null,
            rootMargin: '-20% 0px -70% 0px',
            threshold: 0
        };

        const observerCallback = (entries: IntersectionObserverEntry[]) => {
            entries.forEach((entry) => {
                if (entry.isIntersecting) {
                    setActiveSection(entry.target.id);
                }
            });
        };

        const observer = new IntersectionObserver(observerCallback, observerOptions);
        const sections = document.querySelectorAll("main section[id]");
        sections.forEach((section) => observer.observe(section));

        return () => observer.disconnect();
    }, []);

    return (
        <div className="min-h-screen bg-white text-black font-poppins overflow-x-hidden">
            <Navbar />


            <section className="pt-32 pb-16 px-6 text-center max-w-5xl mx-auto">
                <p
                    className="mb-4 uppercase"
                    style={{
                        fontFamily: "'Poppins', sans-serif",
                        fontWeight: 400,
                        fontStyle: 'normal',
                        fontSize: '13px',
                        lineHeight: '28px',
                        letterSpacing: '0.32em',
                        textAlign: 'center',
                        color: '#000000'
                    }}
                >
                    legal documentation
                </p>
                <h1 className="text-4xl md:text-5xl font-extrabold font-telegraf mb-6 leading-tight text-black">
                    Terms & <span className="text-[#eb5626]">Conditions</span>
                </h1>
                <p className="text-sm text-black max-w-2xl mx-auto leading-relaxed">
                    Please read these terms and conditions carefully before using the <br className="hidden md:block" /> Cardano Africa Tech Summit services.
                </p>
            </section>

            <div className="max-w-7xl mx-auto px-6 pb-24 grid grid-cols-1 lg:grid-cols-12 gap-12 relative">

                <aside className="lg:col-span-3">
                    <div className="sticky top-32 bg-white rounded-xl shadow-sm border border-gray-100 p-8">
                        <h3 className="font-telegraf font-bold text-sm mb-6 uppercase tracking-wider">Table of Contents</h3>
                        <nav className="flex flex-col gap-4">
                            {menuItems.map((item) => (
                                <Link
                                    key={item.id}
                                    href={`#${item.id}`}
                                    onClick={(e) => scrollToSection(e, item.id)}
                                    className={`text-left text-[13px] transition-colors font-medium border-l-2 pl-4 ${activeSection === item.id
                                        ? "text-[#eb5626] border-[#eb5626]"
                                        : "text-black border-transparent hover:text-[#eb5626] hover:border-[#eb5626]"
                                        }`}
                                >
                                    {item.label}
                                </Link>
                            ))}
                        </nav>
                    </div>
                </aside>


                <main className="lg:col-span-9 bg-white rounded-3xl shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-gray-100 p-10 md:p-16">

                    <section id="general" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            General Terms
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                By accessing and placing an order with Cardano Africa Tech Summit, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and Cardano Africa Tech Summit.
                            </p>
                            <p>
                                Under no circumstances shall Cardano Africa Tech Summit team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if Cardano Africa Tech Summit team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.
                            </p>
                            <p>
                                Cardano Africa Tech Summit will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.
                            </p>
                        </div>
                    </section>

                    <section id="license" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            License
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                Cardano Africa Tech Summit grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement.
                            </p>
                            <p>
                                These Terms &amp; Conditions are a contract between you and Cardano Africa Tech Summit (referred to in these Terms &amp; Conditions as &quot;Cardano Africa Tech Summit&quot;, &quot;us&quot;, &quot;we&quot; or &quot;our&quot;), the provider of the Cardano Africa Tech Summit website and the services accessible from the Cardano Africa Tech Summit website. (Which are collectively referred to in these Terms &amp; Conditions as the &quot;Cardano Africa Tech Summit Service&quot;).
                            </p>
                            <p>
                                You are agreeing to be bound by these Terms &amp; Conditions. If you do not agree to these Terms &amp; Conditions, please do not use the Cardano Africa Tech Summit Service. In these Terms &amp; Conditions, &quot;you&quot; refers both to you as an individual and to the entity you represent. If you violate any of these Terms &amp; Conditions, we reserve the right to cancel your account or block access to your account without notice.
                            </p>
                        </div>
                    </section>

                    <section id="definitions" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Definitions and Key Terms
                        </h2>
                        <p className="text-[14px] text-black mb-8">To help explain things as clearly as possible in this Terms & Conditions, every time any of these terms are referenced, are strictly defined as:</p>
                        <div className="grid gap-4">
                            {definitions.map((item, idx) => (
                                <div key={idx} className="bg-[#80B7414D] border border-[#e6f0db] rounded-xl p-5">
                                    <span className="text-[#80b741] font-bold text-xs uppercase tracking-wider block mb-2">{item.term}:</span>
                                    <div className="text-[13px] text-black leading-relaxed font-medium">
                                        {item.term === "Website" ? (
                                            <>
                                                Cardano Africa Tech Summit&apos;s site, which can be accessed via this URL:{" "}
                                                <a
                                                    href="https://cats.wada.org/"
                                                    target="_blank"
                                                    rel="noopener noreferrer"
                                                    className="text-[#eb5626] underline"
                                                >
                                                    https://cats.wada.org/
                                                </a>
                                            </>
                                        ) : (
                                            item.definition
                                        )}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </section>

                    <section id="restrictions" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Restrictions
                        </h2>
                        <p className="text-[14px] text-black leading-[1.8] mb-6">You agree not to, and you will not permit others to:</p>
                        <ul className="list-disc pl-6 space-y-4 text-[14px] text-black">
                            <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website or make the platform available to any third party.</li>
                            <li>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website.</li>
                            <li>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of Cardano Africa Tech Summit or its affiliates, partners, suppliers or the licensors of the website.</li>
                        </ul>
                    </section>

                    <section id="payment" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Payment
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                If you pay for any of our one-time payment plans, you agree to pay all fees or charges to your account for the Service in accordance with the fees, charges and billing terms in effect at the time each fee or charge is due and payable. Your Payment Provider agreement governs your use of the designated credit card account, and you must refer to that agreement and not these Terms to determine your rights and liabilities with respect to your Payment Provider.
                            </p>
                            <p>
                                By providing Cardano Africa Tech Summit with your credit card number and associated payment information, you agree that Cardano Africa Tech Summit is authorized to verify information immediately, and subsequently invoice your account for all fees and charges due and payable to Cardano Africa Tech Summit hereunder and that no additional notice or consent is required. You agree to immediately notify Cardano Africa Tech Summit of any change in your billing address or the credit card used for payment hereunder. Cardano Africa Tech Summit reserves the right at any time to change its prices and billing methods, either immediately upon posting on our Site or by e-mail delivery to your organization&apos;s administrator(s).
                            </p>
                            <p>
                                Any attorney fees, court costs, or other costs incurred in collection of delinquent undisputed
                                amounts shall be the responsibility of and paid for by you. No contract will exist between you and
                                Cardano Africa Tech Summit for the Service until Cardano Africa Tech Summit accepts your order
                                by a confirmatory e-mail, SMS/MMS message, or other appropriate means of communication.
                            </p>
                            <p>
                                You are responsible for any third-party fees that you may incur when using the Service.
                            </p>
                        </div>
                    </section>

                    <section id="refund" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Return and Refund Policy
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                Thanks for shopping at Cardano Africa Tech Summit 2026.
                            </p>
                            <p>
                                We appreciate the fact that you like to purchase the services and commodities on our website. We also want to make sure you have a rewarding experience while you&apos;re exploring, evaluating, and purchasing our products.
                            </p>
                            <p>
                                As with any shopping experience, there are terms and conditions that apply to transactions at Cardano Africa Tech Summit 2026. We&apos;ll be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at Cardano Africa Tech Summit 2026, you agree to the terms along with Cardano Africa Tech Summit&apos;s Privacy Policy.
                            </p>
                            <p>
                                If, for any reason, You are not completely satisfied with any good or service that we provide, don&apos;t hesitate to contact us and we will discuss any of the issues you are going through with our product.
                            </p>
                        </div>
                    </section>

                    <section id="suggestions" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Your Suggestions
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                Any feedback, comments, ideas, improvements or suggestions (collectively, &quot;Suggestions&quot;) provided by you to Cardano Africa Tech Summit with respect to the website shall remain the sole and exclusive property of Cardano Africa Tech Summit.
                            </p>
                            <p>
                                Cardano Africa Tech Summit shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.
                            </p>
                        </div>
                    </section>

                    <section id="links" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Links to Other Websites
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                These Terms & Conditions apply only to the Services. The Services may contain links to other websites not operated or controlled by Cardano Africa Tech Summit. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Terms & Conditions are no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.
                            </p>
                        </div>
                    </section>

                    <section id="cookies" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Cookies
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                Cardano Africa Tech Summit uses &quot;Cookies&quot; to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.
                            </p>
                        </div>
                    </section>

                    <section id="changes" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Changes To Our Terms & Conditions
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                You acknowledge and agree that Cardano Africa Tech Summit may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at Cardano Africa Tech Summit &apos;s sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform Cardano Africa Tech Summit when you stop using the Service. You acknowledge and agree that if Cardano Africa Tech Summit disables access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which are contained in your account. If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date below.
                            </p>
                        </div>
                    </section>

                    <section id="modifications" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Modifications to Our website
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                Cardano Africa Tech Summit reserves the right to modify, suspend or discontinue, temporarily or permanently, the website or any service to which it connects, with or without notice and without liability to you.
                            </p>
                        </div>
                    </section>

                    <section id="updates" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Updates to our website
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                Cardano Africa Tech Summit may from time to time provide enhancements or improvements to the features/ functionality of the website, which may include patches, bug fixes, updates, upgrades and other modifications (&quot;Updates&quot;). Updates may modify or delete certain features and/or functionalities of the website. You agree that Cardano Africa Tech Summit has no obligation to:
                            </p>
                            <ol className="list-decimal pl-6 space-y-2">
                                <li>provide any Updates, or</li>
                                <li>continue to provide or enable any particular features and/or functionalities of the website to you.</li>
                            </ol>
                            <p>
                                You further agree that all Updates will be:
                            </p>
                            <ol className="list-decimal pl-6 space-y-2">
                                <li>deemed to constitute an integral part of the website, and</li>
                                <li>subject to the terms and conditions of this Agreement.</li>
                            </ol>
                        </div>
                    </section>

                    <section id="thirdparty" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Third-Party Services
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services (&quot;Third-Party Services&quot;).
                            </p>
                            <p>
                                You acknowledge and agree that Cardano Africa Tech Summit shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Cardano Africa Tech Summit does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.
                            </p>
                            <p>
                                Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties&apos; terms and conditions.
                            </p>
                        </div>
                    </section>

                    <section id="termination" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Term and Termination
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                This Agreement shall remain in effect until terminated by you or Cardano Africa Tech Summit. Cardano Africa Tech Summit may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.
                            </p>
                            <p>
                                This Agreement will terminate immediately, without prior notice from Cardano Africa Tech Summit, in the event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the website and all copies thereof from your computer.
                            </p>
                            <p>
                                Upon termination of this Agreement, you shall cease all use of the website and delete all copies of the website from your computer.
                            </p>
                            <p>
                                Termination of this Agreement will not limit any of Cardano Africa Tech Summit&apos;s rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.
                            </p>
                        </div>
                    </section>

                    <section id="copyright" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Copyright Infringement Notice
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                If you are a copyright owner or such owner&apos;s agent and believe any material on our website constitutes an infringement on your copyright, please contact us setting forth the following information:
                            </p>
                            <ol className="list-decimal pl-6 space-y-2">
                                <li>a physical or electronic signature of the copyright owner or a person authorized to act on his behalf;</li>
                                <li>identification of the material that is claimed to be infringing;</li>
                                <li>your contact information, including your address, telephone number, and an email;</li>
                                <li>a statement by you that you have a good faith belief that use of the material is not authorized by the copyright owners; and</li>
                                <li>a statement that the information in the notification is accurate, and, under penalty of perjury you are authorized to act on behalf of the owner.</li>
                            </ol>
                        </div>
                    </section>

                    <section id="indemnification" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Indemnification
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                You agree to indemnify and hold Cardano Africa Tech Summit and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys&apos; fees, due to or arising out of your:
                            </p>
                            <ol className="list-decimal pl-6 space-y-2">
                                <li>use of the website;</li>
                                <li>violation of this Agreement or any law or regulation; or</li>
                                <li>violation of any right of a third party.</li>
                            </ol>
                        </div>
                    </section>

                    <section id="warranties" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            No Warranties
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                The website is provided to you &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; and with all faults and defects without warranty of any kind.
                            </p>
                            <p>
                                To the maximum extent permitted under applicable law, Cardano Africa Tech Summit, on its own behalf and on behalf of its affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the website, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, Cardano Africa Tech Summit provides no warranty or undertaking, and makes no representation of any kind that the website will meet your requirements, achieve any intended results, be compatible or work with any other software, websites, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.
                            </p>
                            <p>
                                Without limiting the foregoing, neither Cardano Africa Tech Summit nor any Cardano Africa Tech Summit&apos;s provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the website, or the information, content, and materials or products included thereon; (ii) that the website will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the website; or (iv) that the website, its servers, the content, or e-mails sent from or on behalf of Cardano Africa Tech Summit are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.
                            </p>
                            <p>
                                Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you.
                            </p>
                        </div>
                    </section>

                    <section id="liability" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Limitation of Liability
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                Notwithstanding any damages that you might incur, the entire liability of Cardano Africa Tech Summit and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the website.
                            </p>
                            <p>
                                To the maximum extent permitted by applicable law, in no event shall Cardano Africa Tech Summit or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, for loss of data or other information, for business interruption, for personal injury, for loss of privacy arising out of or in any way related to the use of or inability to use the website, third-party software and/or third-party hardware used with the website, or otherwise in connection with any provision of this Agreement), even if Cardano Africa Tech Summit or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.
                            </p>
                            <p>
                                Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.
                            </p>
                        </div>
                    </section>

                    <section id="severability" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Severability
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.
                            </p>
                            <p>
                                This Agreement, together with the Privacy Policy and any other legal notices published by Cardano Africa Tech Summit on the Services, shall constitute the entire agreement between you and Cardano Africa Tech Summit concerning the Services. If any provision of this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and Cardano Africa Tech Summit&apos;s failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision.
                            </p>
                            <p className="font-bold uppercase">
                                YOU AND Cardano Africa Tech Summit AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.
                            </p>
                        </div>
                    </section>

                    <section id="waiver" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Waiver
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not affect a party&apos;s ability to exercise such right or require such performance at any time thereafter nor shall the waiver of a breach constitute waiver of any subsequent breach.
                            </p>
                            <p>
                                No failure to exercise, and no delay in exercising, on the part of either party, any right or any power under this Agreement shall operate as a waiver of that right or power. Nor shall any single or partial exercise of any right or power under this Agreement preclude further exercise of that or any other right granted herein. In the event of a conflict between this Agreement and any applicable purchase or other terms, the terms of this Agreement shall govern.
                            </p>
                        </div>
                    </section>

                    <section id="amendments" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Amendments to this Agreement
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                Cardano Africa Tech Summit reserves the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision is material we will provide at least 30 days&apos; notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.
                            </p>
                            <p>
                                By continuing to access or use our website after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use Cardano Africa Tech Summit.
                            </p>
                        </div>
                    </section>

                    <section id="entire" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Entire Agreement
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                The Agreement constitutes the entire agreement between you and Cardano Africa Tech Summit regarding your use of the website and supersedes all prior and contemporaneous written or oral agreements between you and Cardano Africa Tech Summit.
                            </p>
                            <p>
                                You may be subject to additional terms and conditions that apply when you use or purchase other Cardano Africa Tech Summit&apos;s services, which Cardano Africa Tech Summit will provide to you at the time of such use or purchase.
                            </p>
                        </div>
                    </section>

                    <section id="updates-terms" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Updates to Our Terms
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                We may change our Service and policies, and we may need to make changes to these Terms so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to these Terms and give you an opportunity to review them before they go into effect. If you continue to use the Service, you will be bound by the updated Terms.
                            </p>
                        </div>
                    </section>

                    <section id="ip" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Intellectual Property
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                The website and its entire contents, features and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are owned by Cardano Africa Tech Summit, its licensors or other providers of such material and are protected by Kenya and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws. The material may not be copied, modified, reproduced, downloaded or distributed in any way, in whole or in part, without the express prior written permission of Cardano Africa Tech Summit, unless and except as is expressly provided in these Terms & Conditions. Any unauthorized use of the material is prohibited.
                            </p>
                        </div>
                    </section>

                    <section id="arbitrate" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Agreement to Arbitrate
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                This section applies to any dispute EXCEPT IT DOESN&apos;T INCLUDE A DISPUTE RELATING TO CLAIMS FOR INJUNCTIVE OR EQUITABLE RELIEF REGARDING THE ENFORCEMENT OR VALIDITY OF YOUR OR Cardano Africa Tech Summit&apos;S INTELLECTUAL PROPERTY RIGHTS.
                            </p>
                            <p>
                                The term &quot;dispute&quot; means any dispute, action, or other controversy between you and Cardano Africa Tech Summit concerning the Services or this agreement, whether in contract, warranty, tort, statute, regulation, ordinance, or any other legal or equitable basis. &quot;Dispute&quot; will be given the broadest possible meaning allowable under law.
                            </p>
                        </div>
                    </section>

                    <section id="dispute" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Notice of Dispute
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                In the event of a dispute, you or Cardano Africa Tech Summit must give the other a Notice of Dispute, which is a written statement that sets forth the name, address, and contact information of the party giving it, the facts giving rise to the dispute, and the relief requested. You must send any Notice of Dispute via email to: <a href="mailto:hello@catsummit.io" className="text-[#eb5626] underline">hello@catsummit.io</a>. Cardano Africa Tech Summit will send any Notice of Dispute to you by mail to your address if we have it, or otherwise to your email address. You and Cardano Africa Tech Summit will attempt to resolve any dispute through informal negotiation within sixty (60) days from the date the Notice of Dispute is sent. After sixty (60) days, you or Cardano Africa Tech Summit may commence arbitration.
                            </p>
                        </div>
                    </section>

                    <section id="binding" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Binding Arbitration
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                If you and Cardano Africa Tech Summit don&apos;t resolve any dispute by informal negotiation, any other effort to resolve the dispute will be conducted exclusively by binding arbitration as described in this section. You are giving up the right to litigate (or participate in as a party or class member) all disputes in court before a judge or jury.
                            </p>
                            <p>
                                The dispute shall be settled by binding arbitration in accordance with the commercial arbitration rules of Chartered Institute of Arbitrators.
                            </p>
                            <p>
                                Either party may seek any interim or preliminary injunctive relief from any court of competent jurisdiction, as necessary to protect the party&apos;s rights or property pending the completion of arbitration. Any and all legal, accounting, and other costs, fees, and expenses incurred by the prevailing party shall be borne by the non-prevailing party.
                            </p>
                        </div>
                    </section>

                    <section id="submissions" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Submissions and Privacy
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                In the event that you submit or post any ideas, creative suggestions, designs, photographs, information, advertisements, data or proposals, including ideas for new or improved products, services, features, technologies or promotions, you expressly agree that such submissions will automatically be treated as non-confidential and non-proprietary and will become the sole property of Cardano Africa Tech Summit without any compensation or credit to you whatsoever. Cardano Africa Tech Summit and its affiliates shall have no obligations with respect to such submissions or posts and may use the ideas contained in such submissions or posts for any purposes in any medium in perpetuity, including, but not limited to, developing, manufacturing, and marketing products and services using such ideas.
                            </p>
                        </div>
                    </section>

                    <section id="promotion" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Promotion
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                Cardano Africa Tech Summit may, from time to time, include contests, promotions, sweepstakes, or other activities (&quot;Promotions&quot;) that require you to submit material or information concerning yourself. Please note that all Promotions may be governed by separate rules that may contain certain eligibility requirements, such as restrictions as to age and geographic location. You are responsible to read all Promotions rules to determine whether or not you are eligible to participate. If you enter any Promotion, you agree to abide by and to comply with all Promotions Rules.
                            </p>
                            <p>
                                Additional terms and conditions may apply to purchases of goods or services on or through the Services, which terms and conditions are made a part of this Agreement by this reference.
                            </p>
                        </div>
                    </section>

                    <section id="typo" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Typographical Errors
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                In the event a product and/or service is listed at an incorrect price or with incorrect information due to typographical error, we shall have the right to refuse or cancel any orders placed for the product and/or service listed at the incorrect price. We shall have the right to refuse or cancel any such order whether or not the order has been confirmed and your credit card charged. If your credit card has already been charged for the purchase and your order is canceled, we shall immediately issue a credit to your credit card account or other payment account in the amount of the charge.
                            </p>
                        </div>
                    </section>

                    <section id="miscellaneous" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Miscellaneous
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                If for any reason a court of competent jurisdiction finds any provision or portion of these Terms & Conditions to be unenforceable, the remainder of these Terms & Conditions will continue in full force and effect.
                            </p>
                            <p>
                                Any waiver of any provision of these Terms & Conditions will be effective only if in writing and signed by an authorized representative of Cardano Africa Tech Summit.
                            </p>
                            <p>
                                Cardano Africa Tech Summit will be entitled to injunctive or other equitable relief (without the obligations of posting any bond or surety) in the event of any breach or anticipatory breach by you.
                            </p>
                            <p>
                                Cardano Africa Tech Summit operates and controls the Cardano Africa Tech Summit Service from its offices in Kenya. The Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation. Accordingly, those persons who choose to access the Cardano Africa Tech Summit Service from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.
                            </p>
                            <p>
                                These Terms & Conditions (which include and incorporate the Cardano Africa Tech Summit Privacy Policy) contains the entire understanding, and supersedes all prior understandings, between you and Cardano Africa Tech Summit concerning its subject matter, and cannot be changed or modified by you.
                            </p>
                            <p>
                                The section headings used in this Agreement are for convenience only and will not be given any legal import.
                            </p>
                        </div>
                    </section>

                    <section id="disclaimer" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Disclaimer
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                Cardano Africa Tech Summit is not responsible for any content, code or any other imprecision.
                            </p>
                            <p>
                                Cardano Africa Tech Summit does not provide warranties or guarantees.
                            </p>
                            <p>
                                In no event shall Cardano Africa Tech Summit be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service.
                            </p>
                            <p>
                                The Company reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.
                            </p>
                            <p>
                                The Cardano Africa Tech Summit Service and its contents are provided &quot;as is&quot; and &quot;as available&quot; without any warranty or representations of any kind, whether express or implied. Cardano Africa Tech Summit is a distributor and not a publisher of the content supplied by third parties; as such, Cardano Africa Tech Summit exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the Cardano Africa Tech Summit Service. Without limiting the foregoing, Cardano Africa Tech Summit specifically disclaims all warranties and representations in any content transmitted on or in connection with the Cardano Africa Tech Summit Service or on sites that may appear as links on the Cardano Africa Tech Summit Service, or in the products provided as a part of, or otherwise in connection with, the Cardano Africa Tech Summit Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by Cardano Africa Tech Summit or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty.
                            </p>
                            <p>
                                Price and availability information is subject to change without notice. Without limiting the foregoing, Cardano Africa Tech Summit does not warrant that the Cardano Africa Tech Summit Service will be uninterrupted, uncorrupted, timely, or error-free.
                            </p>
                        </div>
                    </section>

                    <section id="contact" className="mb-12">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Contact Us
                        </h2>
                        <div className="text-[14px] text-black leading-[1.8] space-y-4">
                            <p>
                                Don&apos;t hesitate to contact us if you have any questions.
                            </p>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>Via Email: <a href="mailto:hello@catsummit.io" className="text-[#eb5626] underline">hello@catsummit.io</a></li>
                            </ul>
                        </div>
                    </section>

                </main>
            </div>


            <section className="bg-[#0a0a0a] w-full print:hidden">
                <div className="max-w-[1440px] mx-auto flex flex-col md:flex-row items-center justify-between gap-5 py-[20px] px-6 min-h-[115px]">
                    <div className="text-center md:text-left">
                        <h2 className="text-white font-telegraf font-extrabold text-2xl lg:text-3xl mb-1">Press Inquiries</h2>
                        <p className="text-white text-sm font-poppins">For media requests and interview opportunities</p>
                    </div>
                    <a
                        href="mailto:team@catsummit.io"
                        className="border border-[#eb5626] !text-[#eb5626] px-8 py-2 rounded-full font-telegraf font-bold hover:bg-[#eb5626] hover:!text-white active:!text-white transition-all duration-300 whitespace-nowrap"
                        style={{ fontSize: '14px' }}
                    >
                        team@catsummit.io
                    </a>
                </div>
            </section>


        </div>
    );
}
