"use client";

import React, { useState, useEffect } from "react";
import Navbar from "@/components/Navbar";
import Link from "next/link";

const definitions = [
    { term: "Cookie", definition: "small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information." },
    { term: "Company", definition: "when this policy mentions 'Company', 'we', 'us' or 'our', it refers to Blockchain Centre Nairobi and Wada Kenya, that is responsible for your information under these Terms & Conditions." },
    { term: "Country", definition: "where Cardano Africa Tech Summit or the owners/founders of Cardano Africa Tech Summit are based, in this case it is Kenya." },
    { term: "Device", definition: "any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Cardano Africa Tech Summit and use the services." },
    { term: "Service", definition: "refers to the service provided by Cardano Africa Tech Summit as described in the relative terms (if available) and on this platform." },
    { term: "Third-party service", definition: "refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you." },
    { term: "Website", definition: "Cardano Africa Tech Summit's site, which can be accessed via this URL: https://cats.wada.org/" },
    { term: "You", definition: "a person or entity that is registered with Cardano Africa Tech Summit to use the Services." },
];

const menuItems = [
    { label: "General Terms", id: "general" },
    { label: "License", id: "license" },
    { label: "Definitions & Key Terms", id: "definitions" },
    { label: "Restrictions", id: "restrictions" },
    { label: "Payment", id: "payment" },
    { label: "Return and Refund Policy", id: "refund" },
    { label: "Your Suggestions", id: "suggestions" },
    { label: "Your Consent", id: "consent" },
];

export default function TermsPage() {
    const [activeSection, setActiveSection] = useState<string>("general");

    const scrollToSection = (e: React.MouseEvent<HTMLAnchorElement>, id: string) => {
        e.preventDefault();
        const element = document.getElementById(id);
        if (element) {
            element.scrollIntoView({ behavior: "smooth", block: "center" });
            window.history.pushState(null, "", `#${id}`);
        }
    };

    useEffect(() => {
        const observerOptions = {
            root: null,
            rootMargin: '-20% 0px -70% 0px',
            threshold: 0
        };

        const observerCallback = (entries: IntersectionObserverEntry[]) => {
            entries.forEach((entry) => {
                if (entry.isIntersecting) {
                    setActiveSection(entry.target.id);
                }
            });
        };

        const observer = new IntersectionObserver(observerCallback, observerOptions);
        const sections = document.querySelectorAll("main section[id]");
        sections.forEach((section) => observer.observe(section));

        return () => observer.disconnect();
    }, []);

    return (
        <div className="min-h-screen bg-white text-black font-poppins overflow-x-hidden">
            <Navbar />

            {/* Hero Section */}
            <section className="pt-32 pb-16 px-6 text-center max-w-5xl mx-auto">
                <p
                    className="mb-4 uppercase"
                    style={{
                        fontFamily: "'Poppins', sans-serif",
                        fontWeight: 400,
                        fontStyle: 'normal',
                        fontSize: '13px',
                        lineHeight: '28px',
                        letterSpacing: '0.32em',
                        textAlign: 'center',
                        color: '#000000'
                    }}
                >
                    legal documentation
                </p>
                <h1 className="text-4xl md:text-5xl font-extrabold font-telegraf mb-6 leading-tight text-black">
                    Terms & <span className="text-[#eb5626]">Conditions</span>
                </h1>
                <p className="text-sm text-black max-w-2xl mx-auto leading-relaxed">
                    Please read these terms and conditions carefully before using the <br className="hidden md:block" /> Cardano Africa Tech Summit services.
                </p>
            </section>

            <div className="max-w-7xl mx-auto px-6 pb-24 grid grid-cols-1 lg:grid-cols-12 gap-12 relative">
                {/* Sidebar Navigation */}
                <aside className="lg:col-span-3">
                    <div className="sticky top-32 bg-white rounded-xl shadow-sm border border-gray-100 p-8">
                        <h3 className="font-telegraf font-bold text-sm mb-6 uppercase tracking-wider">Table of Contents</h3>
                        <nav className="flex flex-col gap-4">
                            {menuItems.map((item) => (
                                <Link
                                    key={item.id}
                                    href={`#${item.id}`}
                                    onClick={(e) => scrollToSection(e, item.id)}
                                    className={`text-left text-[13px] transition-colors font-medium border-l-2 pl-4 ${activeSection === item.id
                                        ? "text-[#eb5626] border-[#eb5626]"
                                        : "text-black border-transparent hover:text-[#eb5626] hover:border-[#eb5626]"
                                        }`}
                                >
                                    {item.label}
                                </Link>
                            ))}
                        </nav>
                    </div>
                </aside>

                {/* Main Content */}
                <main className="lg:col-span-9 bg-white rounded-3xl shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-gray-100 p-10 md:p-16">

                    <section id="general" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            General Terms
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                By accessing and placing an order with Cardano Africa Tech Summit, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and Cardano Africa Tech Summit.
                            </p>
                            <p>
                                Under no circumstances shall Cardano Africa Tech Summit team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if Cardano Africa Tech Summit team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.
                            </p>
                            <p>
                                Cardano Africa Tech Summit will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.
                            </p>
                        </div>
                    </section>

                    <section id="license" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            License
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                Cardano Africa Tech Summit grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement.
                            </p>
                            <p>
                                These Terms &amp; Conditions are a contract between you and Cardano Africa Tech Summit (referred to in these Terms &amp; Conditions as &quot;Cardano Africa Tech Summit&quot;, &quot;us&quot;, &quot;we&quot; or &quot;our&quot;), the provider of the Cardano Africa Tech Summit website and the services accessible from the Cardano Africa Tech Summit website. (Which are collectively referred to in these Terms &amp; Conditions as the &quot;Cardano Africa Tech Summit Service&quot;).
                            </p>
                            <p>
                                You are agreeing to be bound by these Terms &amp; Conditions. If you do not agree to these Terms &amp; Conditions, please do not use the Cardano Africa Tech Summit Service. In these Terms &amp; Conditions, &quot;you&quot; refers both to you as an individual and to the entity you represent. If you violate any of these Terms &amp; Conditions, we reserve the right to cancel your account or block access to your account without notice.
                            </p>
                        </div>
                    </section>

                    <section id="definitions" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Definitions and Key Terms
                        </h2>
                        <p className="text-[14px] text-black mb-8">To help explain things as clearly as possible in this Terms & Conditions, every time any of these terms are referenced, are strictly defined as:</p>
                        <div className="grid gap-4">
                            {definitions.map((item, idx) => (
                                <div key={idx} className="bg-[#80B7414D] border border-[#e6f0db] rounded-xl p-5">
                                    <span className="text-[#80b741] font-bold text-xs uppercase tracking-wider block mb-2">{item.term}:</span>
                                    <div className="text-[13px] text-black leading-relaxed font-medium">
                                        {item.term === "Website" ? (
                                            <>
                                                Cardano Africa Tech Summit&apos;s site, which can be accessed via this URL:{" "}
                                                <a
                                                    href="https://cats.wada.org/"
                                                    target="_blank"
                                                    rel="noopener noreferrer"
                                                    className="text-[#eb5626] underline"
                                                >
                                                    https://cats.wada.org/
                                                </a>
                                            </>
                                        ) : (
                                            item.definition
                                        )}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </section>

                    <section id="restrictions" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Restrictions
                        </h2>
                        <p className="text-[14px] text-black leading-[1.8] mb-6">You agree not to, and you will not permit others to:</p>
                        <ul className="list-disc pl-6 space-y-4 text-[14px] text-black">
                            <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website or make the platform available to any third party.</li>
                            <li>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website.</li>
                            <li>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of Cardano Africa Tech Summit or its affiliates, partners, suppliers or the licensors of the website.</li>
                        </ul>
                    </section>

                    <section id="payment" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Payment
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                If you pay for any of our one-time payment plans, you agree to pay all fees or charges to your account for the Service in accordance with the fees, charges and billing terms in effect at the time each fee or charge is due and payable. Your Payment Provider agreement governs your use of the designated credit card account, and you must refer to that agreement and not these Terms to determine your rights and liabilities with respect to your Payment Provider.
                            </p>
                            <p>
                                By providing Cardano Africa Tech Summit with your credit card number and associated payment information, you agree that Cardano Africa Tech Summit is authorized to verify information immediately, and subsequently invoice your account for all fees and charges due and payable to Cardano Africa Tech Summit hereunder and that no additional notice or consent is required. You agree to immediately notify Cardano Africa Tech Summit of any change in your billing address or the credit card used for payment hereunder. Cardano Africa Tech Summit reserves the right at any time to change its prices and billing methods, either immediately upon posting on our Site or by e-mail delivery to your organization&apos;s administrator(s).
                            </p>
                        </div>
                    </section>

                    <section id="refund" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Return and Refund Policy
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                Thanks for shopping at Cardano Africa Tech Summit. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you have a rewarding experience while you&apos;re exploring, evaluating, and purchasing our products.
                            </p>
                            <p>
                                As with any shopping experience, there are terms and conditions that apply to transactions at Cardano Africa Tech Summit. We&apos;ll be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at Cardano Africa Tech Summit, you agree to the terms along with Cardano Africa Tech Summit&apos;s Privacy Policy.
                            </p>
                            <p>
                                If, for any reason, You are not completely satisfied with any good or service that we provide, don&apos;t hesitate to contact us and we will discuss any of the issues you are going through with our product.
                            </p>
                        </div>
                    </section>

                    <section id="suggestions" className="mb-16">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Your Suggestions
                        </h2>
                        <div className="space-y-6 text-[14px] text-black leading-[1.8]">
                            <p>
                                Any feedback, comments, ideas, improvements or suggestions (collectively, &quot;Suggestions&quot;) provided by you to Cardano Africa Tech Summit with respect to the website shall remain the sole and exclusive property of Cardano Africa Tech Summit.
                            </p>
                            <p>
                                Cardano Africa Tech Summit shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.
                            </p>
                        </div>
                    </section>

                    <section id="consent" className="mb-12">
                        <h2 className="text-2xl font-bold font-telegraf mb-6 border-b border-[#eb5626] pb-4">
                            Your Consent
                        </h2>
                        <div className="text-[14px] text-black leading-[1.8]">
                            <p>
                                We&apos;ve updated our Terms &amp; Conditions to provide you with complete transparency into what is being set when you visit our site and how it&apos;s being used. By using our website, registering an account, or making a purchase, you hereby consent to our Terms &amp; Conditions.
                            </p>
                        </div>
                    </section>

                </main>
            </div>

            {/* Press Inquiries Banner */}
            <section className="bg-[#0a0a0a] w-full print:hidden">
                <div className="max-w-[1440px] mx-auto flex flex-col md:flex-row items-center justify-between gap-5 py-[20px] px-6 min-h-[115px]">
                    <div className="text-center md:text-left">
                        <h2 className="text-white font-telegraf font-extrabold text-2xl lg:text-3xl mb-1">Press Inquiries</h2>
                        <p className="text-white text-sm font-poppins">For media requests and interview opportunities</p>
                    </div>
                    <a
                        href="mailto:team@catsummit.io"
                        className="border border-[#eb5626] !text-[#eb5626] px-8 py-2 rounded-full font-telegraf font-bold hover:bg-[#eb5626] hover:!text-white active:!text-white transition-all duration-300 whitespace-nowrap"
                        style={{ fontSize: '14px' }}
                    >
                        team@catsummit.io
                    </a>
                </div>
            </section>


        </div>
    );
}
